Imports:

In [6]:
import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Data cleaning:

In [11]:
df = pd.read_csv("dino_clean.csv")
df

,name,pronunciation,meaning,type,length,weight,diet,teeth,food,how_moved,...,site3,site4,era,time_range,start,end,weight_clean,meaning_clean,year_clean,herbivorous
0,Aardonyx,ar-don-ix,'Earth claw',prosauropod,8.0m,NaN,herbivorous,NaN,NaN,NaN,...,NaN,NaN,Early Jurassic,199-189 million years ago,199.0,189.0,NaN,Earth claw,2009.0,1.0
1,Abelisaurus,ah-BEEL-ee-sore-us,'Abel's lizard',large theropod,9.0m,NaN,carnivorous,NaN,NaN,NaN,...,NaN,NaN,Late Cretaceous,74-70 million years ago,74.0,70.0,NaN,Abel's lizard,1985.0,0.0
2,Achelousaurus,ah-KEL-oo-SORE-us,'Achelous' lizard',ceratopsian,6.0m,NaN,herbivorous,NaN,NaN,NaN,...,NaN,NaN,Late Cretaceous,83-70 million years ago,83.0,70.0,NaN,Achelous' lizard,1995.0,1.0
3,Achillobator,a-kil-oh-bah-tor,'Achilles hero',large theropod,5.0m,NaN,carnivorous,NaN,NaN,NaN,...,NaN,NaN,Late Cretaceous,99-84 million years ago,99.0,84.0,NaN,Achilles hero,1999.0,0.0
4,Acrocantho-saurus,ah-kroh-kan-tho-SORE-us,'high-spined lizard',large theropod,12.0m,NaN,carnivorous,NaN,NaN,NaN,...,NaN,NaN,Early Cretaceous,115-105 million years ago,115.0,105.0,NaN,high-spined lizard,1950.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,Yunnanosaurus,yoo-nahn-oh-sore-us,'Yunnan lizard',prosauropod,7.0m,NaN,omnivorous,NaN,NaN,NaN,...,NaN,NaN,Early Jurassic,205-190 million years ago,205.0,190.0,NaN,Yunnan lizard,1942.0,0.0
314,Yutyrannus,YOO-tie-ran-us,'feathered tyrant',large theropod,7.5m,1100kg,carnivorous,NaN,NaN,NaN,...,NaN,NaN,Early Cretaceous,125 million years ago,125.0,125.0,1100.0,feathered tyrant,2012.0,0.0
315,Zalmoxes,zal-moks-eez,'Zalmoxes (Dacian deity)',small ornithopod,3.0m,NaN,herbivorous,NaN,NaN,NaN,...,NaN,NaN,Late Cretaceous,69 million years ago,69.0,69.0,NaN,Zalmoxes (Dacian deity),1902.0,1.0
316,Zephyrosaurus,ZEF-ear-ro-SORE-us,'west wind lizard',small ornithopod,1.8m,NaN,herbivorous,NaN,NaN,NaN,...,NaN,NaN,Early Cretaceous,120-110 million years ago,120.0,110.0,NaN,west wind lizard,1980.0,1.0
317,Zuniceratops,zoo-nee-serra-tops,'Zuni (the name of a tribe of Indigenous Peopl...,ceratopsian,NaN,NaN,herbivorous,NaN,NaN,NaN,...,NaN,NaN,Late Cretaceous,94-89 million years ago,94.0,89.0,NaN,Zuni (the name of a tribe of Indigenous People...,1998.0,1.0

In [12]:
df.isnull().any()

name              False
pronunciation     False
meaning           False
type              False
length             True
weight             True
diet              False
teeth              True
food               True
how_moved          True
when_it_lived      True
found_it          False
taxonomy          False
foundators        False
year               True
species_type      False
comments           True
img_url           False
length_clean       True
diet_clean         True
taxonomy_depth    False
site1             False
site2              True
site3              True
site4              True
era                True
time_range         True
start              True
end                True
weight_clean       True
meaning_clean      True
year_clean         True
herbivorous        True
dtype: bool

In [13]:
df.shape

(318, 33)

In [24]:
df["length"].to_string("height.txt", index = False)
deleted = df[df["length"].isnull()]
deleted.to_csv("deleted.txt", index = False)

In [35]:
df.dropna(axis = 1, thresh = 300) #300

,name,pronunciation,meaning,type,length,diet,when_it_lived,found_it,taxonomy,foundators,...,diet_clean,taxonomy_depth,site1,era,time_range,start,end,meaning_clean,year_clean,herbivorous
0,Aardonyx,ar-don-ix,'Earth claw',prosauropod,8.0m,herbivorous,"Early Jurassic, 199-189 million years ago",South Africa,"Dinosauria, Saurischia, Sauropodomorpha, Prosa...","Yates, Bonnan, Neveling, Chinsamy and Blackbeard",...,herbivorous,5,SouthAfrica,Early Jurassic,199-189 million years ago,199.0,189.0,Earth claw,2009.0,1.0
1,Abelisaurus,ah-BEEL-ee-sore-us,'Abel's lizard',large theropod,9.0m,carnivorous,"Late Cretaceous, 74-70 million years ago",Argentina,"Dinosauria, Saurischia, Theropoda, Neotheropod...",Bonaparte and Novas,...,carnivorous,7,Argentina,Late Cretaceous,74-70 million years ago,74.0,70.0,Abel's lizard,1985.0,0.0
2,Achelousaurus,ah-KEL-oo-SORE-us,'Achelous' lizard',ceratopsian,6.0m,herbivorous,"Late Cretaceous, 83-70 million years ago",USA,"Dinosauria, Ornithischia, Neornithischia, Cera...",Sampson,...,herbivorous,10,USA,Late Cretaceous,83-70 million years ago,83.0,70.0,Achelous' lizard,1995.0,1.0
3,Achillobator,a-kil-oh-bah-tor,'Achilles hero',large theropod,5.0m,carnivorous,"Late Cretaceous, 99-84 million years ago",Mongolia,"Dinosauria, Saurischia, Theropoda, Dromaeosaur...","Perle, Norell and Clark",...,carnivorous,4,Mongolia,Late Cretaceous,99-84 million years ago,99.0,84.0,Achilles hero,1999.0,0.0
4,Acrocantho-saurus,ah-kroh-kan-tho-SORE-us,'high-spined lizard',large theropod,12.0m,carnivorous,"Early Cretaceous, 115-105 million years ago","Canada,\r\n\t\t\t\t\t\t\r\n\t\t\t\t\t\t\tUSA","Dinosauria, Saurischia, Theropoda, Carcharodon...",Stovall and Langston,...,carnivorous,4,Canada,Early Cretaceous,115-105 million years ago,115.0,105.0,high-spined lizard,1950.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,Yunnanosaurus,yoo-nahn-oh-sore-us,'Yunnan lizard',prosauropod,7.0m,omnivorous,"Early Jurassic, 205-190 million years ago",China,"Dinosauria, Saurischia, Sauropodomorpha, Prosa...",Young,...,omnivorous,5,China,Early Jurassic,205-190 million years ago,205.0,190.0,Yunnan lizard,1942.0,0.0
314,Yutyrannus,YOO-tie-ran-us,'feathered tyrant',large theropod,7.5m,carnivorous,"Early Cretaceous, 125 million years ago",China,"Dinosauria, Saurischia, Theropoda, Tyrannosaur...",Xu and colleagues,...,carnivorous,4,China,Early Cretaceous,125 million years ago,125.0,125.0,feathered tyrant,2012.0,0.0
315,Zalmoxes,zal-moks-eez,'Zalmoxes (Dacian deity)',small ornithopod,3.0m,herbivorous,"Late Cretaceous, 69 million years ago",Romania,"Dinosauria, Ornithischia, Ornithopoda, Euornit...",Nopcsa,...,herbivorous,6,Romania,Late Cretaceous,69 million years ago,69.0,69.0,Zalmoxes (Dacian deity),1902.0,1.0
316,Zephyrosaurus,ZEF-ear-ro-SORE-us,'west wind lizard',small ornithopod,1.8m,herbivorous,"Early Cretaceous, 120-110 million years ago",USA,"Dinosauria, Ornithischia, Ornithopoda, Euornit...",Sues,...,herbivorous,4,USA,Early Cretaceous,120-110 million years ago,120.0,110.0,west wind lizard,1980.0,1.0
317,Zuniceratops,zoo-nee-serra-tops,'Zuni (the name of a tribe of Indigenous Peopl...,ceratopsian,NaN,herbivorous,"Late Cretaceous, 94-89 million years ago",USA,"Dinosauria, Ornithischia, Neornithischia, Cera...",Wolfe and Kirkland,...,herbivorous,8,USA,Late Cretaceous,94-89 million years ago,94.0,89.0,Zuni (the name of a tribe of Indigenous People...,1998.0,1.0

In [4]:
import pandas as pd

# --------------------
# LOAD DATA
# --------------------
df = pd.read_csv("dino_clean.csv")

# --------------------
# BASIC CLEANING
# --------------------
# Make a copy
dino = df.copy()

# 1) Standardize text columns
text_cols = ['type', 'diet', 'taxonomy', 'era', 'site1', 'site2', 'site3', 'site4']
for col in text_cols:
    dino[col] = dino[col].astype(str).str.strip().str.lower()

# 2) Fill missing 'era' using 'time_range' (basic extraction)
dino['era'] = dino['era'].fillna(
    dino['time_range'].astype(str).str.extract(r'(triassic|jurassic|cretaceous)', expand=False)
)

# 3) Derived columns
dino['lifespan'] = dino['start'] - dino['end']  # For Q2
site_cols = ['site1', 'site2', 'site3', 'site4']
dino['sites'] = dino[site_cols].apply(
    lambda row: ', '.join([x for x in row if x and x != 'nan']), axis=1
)

# 4) Keep only important columns
important_cols = [
    'name', 'type', 'length_clean', 'weight_clean', 'diet_clean',
    'taxonomy', 'taxonomy_depth', 'era', 'start', 'end',
    'lifespan', 'sites', 'year_clean', 'herbivorous'
]
dino_cleaned = dino[important_cols]

# 5) Remove duplicates & replace blank strings with NaN
dino_cleaned = dino_cleaned.drop_duplicates(subset='name')
dino_cleaned = dino_cleaned.replace(['', 'nan', 'NaN', 'None'], pd.NA)

print("✅ Basic cleaning complete!")
print(dino_cleaned.head())

✅ Basic cleaning complete!
                name            type  length_clean  weight_clean   diet_clean  \
0           Aardonyx     prosauropod           8.0           NaN  herbivorous
1        Abelisaurus  large theropod           9.0           NaN  carnivorous
2      Achelousaurus     ceratopsian           6.0           NaN  herbivorous
3       Achillobator  large theropod           5.0           NaN  carnivorous
4  Acrocantho-saurus  large theropod          12.0           NaN  carnivorous

                                            taxonomy  taxonomy_depth  \
0  dinosauria, saurischia, sauropodomorpha, prosa...               5
1  dinosauria, saurischia, theropoda, neotheropod...               7
2  dinosauria, ornithischia, neornithischia, cera...              10
3  dinosauria, saurischia, theropoda, dromaeosaur...               4
4  dinosauria, saurischia, theropoda, carcharodon...               4

                era  start    end  lifespan        sites  year_clean  \
0    early jurassic  199.0  189.0      10.0  southafrica      2009.0
1   late cretaceous   74.0   70.0       4.0    argentina      1985.0
2   late cretaceous   83.0   70.0      13.0          usa      1995.0
3   late cretaceous   99.0   84.0      15.0     mongolia      1999.0
4  early cretaceous  115.0  105.0      10.0  canada, usa      1950.0

   herbivorous
0          1.0
1          0.0
2          1.0
3          0.0
4          0.0

In [2]:
df = pd.read_csv("dino_clean.csv")
df.to_excel("dino_clean.xlsx")

In [7]:
plt.figure(figsize=(10, 6))
sns.histplot(
    data=df,
    x='era',
    hue='continent',
    multiple='stack',
    palette='tab20',
    order=[
        "early triassic", "mid triassic", "late triassic",
        "early jurassic", "mid jurassic", "late jurassic",
        "early cretaceous", "late cretaceous"
    ]
)

plt.title("Continental Drift and Dinosaur Distribution")
plt.xlabel("Geological Era")
plt.ylabel("Number of Species")
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

ValueError: Could not interpret value `continent` for `hue`. An entry with this name does not appear in `data`.

In [3]:
country_to_continent = {
    "USA": "North America",
    "Canada": "North America",
    "China": "Asia",
    "India": "Asia",
    "Argentina": "South America",
    # Add more mappings...
}

df['continent'] = df['found_it'].map(country_to_continent)